export const siteUrl = new URL("https://nexxcloud.org");
export const repositoryUrl = "https://github.com/ShadowSafin/NexxCloud";
export const releasesUrl = `${repositoryUrl}/releases/latest`;

export const siteConfig = {
  name: "NexxCloud",
  title: "NexxCloud | Self-Hosted Cloud Storage, File Sharing & Docker Apps",
  description:
    "Deploy NexxCloud on your own hardware for private cloud storage, resumable huge uploads, bulk downloads, LAN access, live server logs, native clients, and Docker Hub app hosting.",
  shortDescription: "Private cloud storage and Docker apps on your own hardware.",
  keywords: [
    "NexxCloud",
    "Nexx Cloud",
    "NexxCloud app",
    "NexxCloud storage",
    "NexxCloud cloud storage",
    "NexxCloud file manager",
    "NexxCloud cloud drive",
    "NexxCloud personal cloud",
    "NexxCloud private cloud",
    "NexxCloud file upload",
    "NexxCloud file download",
    "NexxCloud desktop app",
    "NexxCloud Windows app",
    "NexxCloud Android app",
    "NexxCloud storage client",
    "NexxCloud secure file transfer",
    "NexxCloud Docker apps",
    "NexxCloud Docker Hub",
    "NexxCloud LAN access",
    "NexxCloud bulk download",
    "NexxCloud server app",
    "NexxCloud live logs",
    "self-hosted cloud storage",
    "private cloud storage",
    "personal cloud storage",
    "secure cloud storage",
    "self-hosted file storage",
    "cloud drive",
    "cloud file manager",
    "cloud storage software",
    "private file hosting",
    "secure file transfer",
    "large file transfer",
    "secure upload",
    "secure download",
    "cloud upload",
    "cloud download",
    "Windows cloud storage",
    "Android cloud storage",
    "desktop cloud storage",
    "mobile cloud storage",
    "cross platform cloud",
    "privacy focused storage",
    "Docker cloud storage",
    "Docker app marketplace",
    "Docker Hub app hosting",
    "self-hosted Docker apps",
    "LAN cloud storage",
    "bulk folder download",
    "resumable huge uploads",
    "home server apps",
    "Windows cloud server",
    "NAS file storage",
  ],
  locale: "en_US",
  language: "en-US",
};
